application: hello-aman
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /.*
  script: hello-aman.app

libraries: 
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.1"
- name: PIL
  version: "1.1.7"

